### ISSUE TITLE
UI and API access of the same dokimion database - any need for a lock ?

### ISSUE THREAD

**Issue by bobbeck55** [sillsdev/dokimion#87]
Access of the same dokimion database via the UI and the API (updater) tool - can it one user write on top of the other user's changes? Is a lock needed ?

**Comment by mpelley** [comment]
I don't think so.  Since the UI uses the API, everything gets funneled through the same API.  The backend has a built-in mechanism to prevent two users changing the same test case at the same time.   It uses the "last saved time".  A request to change a test case includes the "last saved time" of what it started with to do the edit.  If that doesn't match what is in the database, the request is rejected.  When a change is accepted, the backend fills in a new "last saved time".

**Comment by bobbeck55** [comment]
if the updater tool GETs a testcase via the api , modifies it and saves it in a file, the UI then changes the testcase, and then the updater tool attempts to change the previously fetched testcase, the dokimion api will reject the request and give the user the option to overwrite the testcase.
